language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run build
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: codydevbox@gmail.com
  api_key:
    secure: R7NYRyRB1oIw6G+Dpzw5NgdaIQirt1KE0Wh9cH14cvIOwj37LUcuXZqQADWnrItABqg8xVRichCnFPB6UQp/pVaBO04Bz2cKH9MBYx+C0oAI/7Yk7i02yJcJnkamjdI8kBEhV98ewxJiFqEEr1f3iJQ2duiPZESMP5xUgS42B7oHS/9nB7m3+/u9GELyF2EyHK7K8169EkDCXDtyq7d77eQdZAjdSqkJ8GK4BreHS2O1j+ykdOyvz0mLLQoaak/HUrXovmjLqXEObzAoqnwoT32fFrLLiyLfZvRsN0K3RoQY6JMAZtUkuiDiT7ReeG4KDLljNFZdAbZfekEoI5z+sq6KObh80Erb3baFh/dTpUCbOzmqlyh060QO8wrD48kc9cHeKIhmLZtb3L6xknFpBzxflpO6jIsXLmqVOyHHHWy85t+oLC2oQDY9FbdbQvTdbvskwkNjbWBpArCprrudFmWBy9jOjZZvb6IjcLBIeufKjO6B+A4tEzQJj6HU6sCGOoVEbJk2sxZtHrD0aQtJn/ixMuBiWwDG0jtlyA9I6E9Bt2sPlI8naY/niFZAv9tOhMJaApiOozWTsgamAYn9jpAFbCaS27PR1E6ZtfrJG1UB5+gqcIntoanXYVyRGQZbnsYTGcTOxL8hCemua9q5RxtmcAfKCc12quLxEiC/+is=
  on:
    branch: master
    repo: codyjdalton/super-injector
