language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run build
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: codydevbox@gmail.com
  api_key:
    secure: pPgPZ7lcV2Zky6nD6Zpw6zikXUmt8cy3O2cFKntW2KI97iYjBc3HfB0aflP6YK2lA0+cWOZlHiC2im4cpKjsPaVcxQMGveeAmBitXPQpE7ndCZMzCZd21wO2zsGZn9cp98pbIOiDIuxwMIF22qhBgJbaqhni6mi+G7iuk/ckVFLj/q9ErZZZ6aNmIC/yvbp7LrPqmnvi/HcfH9wEsTxgJLaMWDWDg5WYanX11JFTmJAZJbcOFzJ+dJYgrV3quDCKDCRo+SspXkaSbd8g4O3FbWY1WLm+XfMc4auUts5WCFoCbRy8Wk9gnpnfChw8Hevzve/XQs1jPTdKme9HIUfS9hHJdFcX6F4t2p9CgOy6X/Vvoztz6wKEYxND/1zL19EBfLT8VbUmj01RLrInoaXTKvS0C9W6TAOFGgP3zi4zhSOPm7+qsjMJhtQQNtcFK8s6IdXZzLuNTE4XKDMf0nxiKp4NXlNCmNKRzujapQU7Da0ueUlsUT3CVW5qeNGCaRxHL1x/3H+y4W0yqZxIneH8QIBmG1nGuXfnm5srI3NJ9gqgQJl649VnutEvzuLtGJPK547lp+z+McfZfuAvZ9lxNq79tjIO0TUbREpnOlFkqAt1oIGoftALqkKHZ9XrwxLGz+l7FQLQoDmqG+iYth9p51APHTgBMl4RtqH/PEu4N6g=
  on:
    branch: master
    repo: codyjdalton/super-injector
